### PR TITLE
[wip] daemon.xml:non_ranged attack particle effect

### PR DESCRIPTION
**Pull request by andy5995**
I had an idea to add some particle effects to non-ranged units, so there would actually be more of a visual when non-ranged units are attacking.

Anyone else think this would be a useful and visually appealing feature?

This screenie doesn't show it well, but there are "smoky" particles around the daemon as he is attacking the golem.

But the particle effect doesn't really look good for this situation. And it would be better if the particles were less on the attacking unit, and more on the unit that is being attacked.

Anyone want to take a crack at this? Or tell me how to make this look good? 

screen128

### CODE REVIEW

**Comment by andy5995** [comment]
>And it would be better if the particles were less on the attacking unit, and more on the unit that is being attacked.

I used the xml file from the Egypt priest to get the desired effect.

It will need some tweaking, but I'll merge now so we can try it out a little.

**Comment by KeithSammut** [comment]
I know how to do this, I can add sword slashing effects to swords

**Comment by andy5995** [comment]
Cool. :) Whenever you get around to it, I'd like to see an improvement on what I've done. We'll just do a few units at first, so we can see how we all like it before making the changes "universal". But you can do either just one, or a few, depending on your interest at the time ;)

**Comment by KeithSammut** [comment]
I'm trying to do the daemon, but although the direction of the particles is correct, they are only showing up for one slash per attack

**Pull request merged**
