### PR TITLE
power_golem:reduce armor to 20

### PR DESCRIPTION
**Pull request by andy5995**
In Discord, @KeithSammut suggested reducing the armor to 20 and no one
disagreed xD

### CODE REVIEW

**Comment by mathusummut** [comment]
I slightly disagree with this, I think this would weaken the Power Golem a bit too much.

**Comment by andy5995** [comment]
Ok.. I wouldn't mind if it's not merged yet, pending further discussion

**Comment by Jammyjamjamman** [comment]
I think this will be fine. The attack is so strong on golems that if you get ~8, they're really hard to get near. It would give players a chance to kill them if they get near.

**Comment by mathusummut** [comment]
Ok, I will merge this then.

**Pull request merged**
