### PR TITLE
[discussion] implement traders

### PR DESCRIPTION
**Pull request by andy5995**
For example, you can buy gold with stone.

This is just a demo, not to be merged.

### CODE REVIEW

**Comment by Jammyjamjamman** [comment]
I think this would make the game more interesting :)

**Comment by mathusummut** [comment]
I don't think this should be added, as scavenging the map for resources because your workers have mined it all is part of the frantic nature of the game.

**Comment by andy5995** [comment]
>I don't think this should be added, as scavenging the map for resources because your workers have mined it all is part of the frantic nature of the resource acquisition part of the game.

I agree, but I see at least 2 compelling reasons to make a change like this:

* Traders or trading posts are an in-demand feature.
* It's really not much fun for me, or other players, to play a game for 40 minutes, only to lose because gold or some other resource is inaccessible.

So if we did a change like this, it shouldn't be an "easy" fix to get extra gold or other resources.

For instance, notice that each player starts with 1 trader. So if he gets killed, that's the end of trading. :)

But one thing that should get  changed is when a trader is allowed to trade, so he can't trade very early in the game.

Also.. we can raise the price.. 1000 stone for 100 gold..  2000 wood for 100 stone or 100 gold.

And also, the time it takes to make the trade can be increased.

**Comment by mathusummut** [comment]
Ok, with those restrictions in place I guess it would make sense.

**Comment by andy5995** [comment]
I opened a ticket for this: #29

**Comment by andy5995** [comment]
>Just to add, we could make trading a "skill".

Yeah, we'll do it in a tidy way. :) I just made the "demo" to start a discussion about it. xD

**Pull request closed without merging**
