### PR TITLE
Specialists: Made Flying Models More Realistic!

### PR DESCRIPTION
**Pull request by KeithSammut**

### CODE REVIEW

**Comment by andy5995** [comment]
I'm not good at reviewing models. @MirceaKitsune and @Jammyjamjamman have a much better eye for that sort of thing.

But I've got some screenshots here

image

screen73
screen74
screen75

**Comment by MirceaKitsune** [comment]
The model itself looks pretty good. My only problem is that the Specialists faction is out of place in contrast to the others, plus its overall quality is questionable... I for one am for removing that faction from the default Zetaglest pack. Will wait to see what others say on this one.

**Comment by andy5995** [comment]
Thanks again for the feedback, @MirceaKitsune 

>My only problem is that the Specialists faction is out of place in contrast to the others, plus its overall quality is questionable... I for one am for removing that faction from the default Zetaglest pack. Will wait to see what others say on this one.

I've seen you mention this a couple times before. I expect that at some point, there may be an extended discussion about it as we decide what factions will be in the official first release. (or there may be factions removed in subsequent releases).

Right now, I think the folks who are actively working on ZG are focused on a few things other than ZG so spread a bit thin.

@Jammyjamjamman has recently played the Specialists faction more often to help test it further. I weigh his opinion very highly because he has been a core Glest player for several years, and it was he and I who decided to fork ZetaGlest and MegaGlest.

The  Specs. faction has been worked on by @mathusummut and @KeithSammut . @mathusummut has been a huge contributor to ZG, in the last 5 months since it was started, and currently one of the admins.

As for your concern about the quality of the models in the Specs. faction, Keith is frequently updating models. And the goal of ZG is to accept contributions from many artists. In October, we will get a huge influx of contributors from [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

Especially when people put a lot of work into a faction, it's nice not to have it only in the mod center. I've noticed with MG, once in the mod center, it rarely gets played or updated. The mod, Assault Command by @Ishmaru, for example. An extremely high-quality mod that rarely gets played.

As for other contrast you mentioned, I'm not sure what you meant. :) The technology it uses? Could you explain that further?

**Comment by MirceaKitsune** [comment]
@andy5995 I see. There were a few reasons why the Specs faction seemed out of place to me:

- The technology level was one. It felt like they're an oddly futuristic faction among medieval themed societies, which for Zetapack seems to break the set at a first sight.
- The main issue I had is that a lot of the models look poorly textured, with many simplistically colored areas for instance. Of course this can be improved over time.
- Another big problem for me were the music and splash screen, which further didn't feel like they fit in. Admittedly that made the faction feel more like a meme.

Perhaps I shouldn't be thinking of removing it, but rather of improving it to fix those issues. In that regard this model definitely does a good job! I tend to want everything to be clean and of top quality, which is why I never liked the factions added in MegaGlest and only ever looked at Magitech as top quality content. My views can be flawed and sometimes not in line with the view others have of the project... I can learn to understand that and correct it when it's the case.

**Comment by andy5995** [comment]
@MirceaKitsune We appreciate that you care about this project, and your eye for details, both artistic and conceptual. You bring up good points that I think are worth discussion at some point, if for no other reason, than to elaborate on the ZG goals to make them more clear.

Early on, I quickly wrote out some [Project Goals](https://github.com/ZetaGlest/zetaglest-source#why-this-fork-project-goals) but they haven't been updated or expanded upon yet.

Right now I think we're focusing on mostly having fun, learning git, practicing skills, and giving others/future contributors the opportunity to practice their skills. But we would also of course like a game that is just fun to play, with graphics that can compete with modern games.

I don't worry about contrast too much because I'm so used to playing MegaPack, with its mix of Persian Genies, Egyptian snakes, and a tech faction that never existed. ;)

And as a side-note, it may interest you to know that @mathusummut is working on some exciting changes with regard to incorporating LUA to add new features.

You can see #29 , https://github.com/ZetaGlest/zetaglest-source/issues/35 , and https://github.com/ZetaGlest/zetaglest-source/commit/d1acd8742395bca8b37656e9e8065022902586fe to get a sneak-peek :)

**Pull request merged**
