### PR TITLE
specialists:add wheat field to starting units

### PR DESCRIPTION
**Pull request by andy5995**
This fixes the problem I reported on Discord, where the Specialists only
create 4 or 5 units.

### CODE REVIEW

**Comment by mathusummut** [comment]
Did this actually fix the issue for you?

**Comment by andy5995** [comment]
yes

**Comment by andy5995** [comment]
the ai-behavior tag isn't necessary, but we may want to use it later.

**Comment by mathusummut** [comment]
Oh, I could not reproduce the issue because I was playing on a version that did not have the AI "fix" we had done to reduce network lag. Apparently that "fix" has caused the issue.

**Comment by andy5995** [comment]
Oh.. interesting. (FYI @Jammyjamjamman .. figured you'd want a note about this).

**Pull request merged**
