### PR TITLE
Added colosseum image and changed it's name

### PR DESCRIPTION
**Pull request by KeithSammut**

### CODE REVIEW

**Comment by andy5995** [comment]
Looks, and sounds good to me! But with a PR of this magnitude, it will need also to be reviewed by @Jammyjamjamman and @mathusummut before merging.

**Comment by mathusummut** [comment]
I approve, the changes look proper. :)

**Comment by KeithSammut** [comment]
haha my brother is an HOD

**Comment by Jammyjamjamman** [comment]
The models look really nice! I'm happy to let this go through, but here's just a few thoughts I had:

* the new models have a high triangle count, which is bad for weak GPU's (I'm not too worried by this one, because it has to be a very old GPU to be a problem, and not too many Colosseum's are built so the quantities of tris won't increase too much).
* Some of the textures are a bit plain. I reckon the temple roof would nicer with e.g. the texture of the arrow tower roof.
* Units cannot walk through the Colusseum, which could be problematic on cramped maps (but actually, I don't really like cramped maps).

Another thing I would suggest regarding admin-stuff, I think it's ok to let major changes to go through as long as 2 admins agree :) .

**Comment by andy5995** [comment]
>Another thing I would suggest regarding admin-stuff, I think it's ok to let major changes to go through as long as 2 admins agree :) .

I figured that in this case, @mathusummut might be biased!

**Comment by Jammyjamjamman** [comment]
That's true! As long as one moderator is not family, I think it's fine. I think we're pretty safe for this project, as long as @mathusummut and @KeithSammut don't try to implement a ransomware or something similar ;-).

- [ ]

**Comment by andy5995** [comment]
I actually noticed the plain-ness of the temple roof too. When I zoomed in on things, everything looked real cool, though.

>I reckon the temple roof would nicer with e.g. the texture of the arrow tower roof.

@Jammyjamjamman I didn't know what  that referred to.

**Comment by Jammyjamjamman** [comment]
The arrow tower uses a tile texture on the roof. https://drive.google.com/file/d/1gkV-llpysPIBw1BHUwiBQ4KvZwH0y4HZ/view?usp=sharing

I think it may look nice as a texture on the temple roof (if applied better than it was on the arrow tower ;-) )

**Comment by andy5995** [comment]
Should we demand that change be made before the PR is merged? haha

**Comment by mathusummut** [comment]
The merge includes the new menu music as well...may I suggest merge now fix later?

**Comment by andy5995** [comment]
yes.. I'll do that. But another reminder.. patches unrelated or independent of each other should be in separate pull requests, esp. so a problem with a single patch does not hold up the entire pull request.

**Comment by KeithSammut** [comment]
im working on these at the moment @Andy

**Comment by andy5995** [comment]
Thank you! Me and Jammy left some extra comments and suggestions in the #modelling channel.

**Pull request merged**
