### PR TITLE
Updates :D

### PR DESCRIPTION
**Pull request by KeithSammut**

### CODE REVIEW

**Comment by mathusummut** [comment]
I will merge this. The "medieval" faction may have its name changed in the future.

**Comment by andy5995** [comment]
Could someone please make sure these new factions work. I tried starting a game with them and ZG crashed

```Message: Error loading UnitType: /home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/medieval/units/sorcerer/sorcerer.xml
Message: Error opening wav file: /home/andy/src/zg-local/zetaglest-data/techs/zetapack//commondata//sounds/archmage_attack17.wav]```

**Comment by mathusummut** [comment]
Oh, I'm having the same issue. Let me fix it really quick.

**Comment by mathusummut** [comment]
It should work properly now.

**Comment by andy5995** [comment]
Thanks, Matt

**Pull request merged**
