### PR TITLE
 Changed intro and menu music + roman forum and temple models

### PR DESCRIPTION
**Pull request by KeithSammut**
Happy Birthday Andy!

### CODE REVIEW

**Comment by andy5995** [comment]
Thank for for doing this is @KeithSammut .

I've decided that if we decide to remove the menu animations, that can be done at a later time, so we can use your work.

Please review https://github.com/ZetaGlest/zetaglest-source/blob/develop/CONTRIBUTING.md for the contributing guidelines, there are a few problems with this pull request.

You would need to separate the changes to romans in a separate PR. The reasons for doing so are mentioned in the CONTRIBUTING doc.

Also, as I mentioned in Discord, before working on contribution, you'll need to open a ticket first. More info about that is mentioned in the CONTRIBUTING doc.

When you make changes, you should create separate branch. So in this case, you would have needed to make 2 separate branches. One for the roman models, and one for the rest. Some details about that are also in the doc I mentioned above.

This time, we'll keep this pull request as it is. There's no need for you to resubmit and split the patches into 2 separate pull requests. But in the future, I will have to be more strict! :)

The only change that needs to be made is that when clicking the worker to build, the option to build a "forum" is there; that needs to be changed to "colosseum".

Thank you for the birthday wishes, and for the contributions! :)

**Comment by KeithSammut** [comment]
but I didn't think of changing it to colosseum. isn't the colosseum a type
of forum?

**Comment by andy5995** [comment]
It produces like a forum, but with your patch, the name of the unit is now a Colosseum.

And technically, they are 2 different things

From https://en.wikipedia.org/wiki/Roman_Forum

>For centuries the Forum was the center of day-to-day life in Rome: the site of triumphal processions and elections; the venue for public speeches, criminal trials, and gladiatorial matches; and the nucleus of commercial affairs. Here statues and monuments commemorated the city's great men.

https://en.wikipedia.org/wiki/Colosseum

>The Colosseum could hold, it is estimated, between 50,000 and 80,000 spectators,[5][6] having an average audience of some 65,000;[7][8] it was used for gladiatorial contests and public spectacles such as mock sea battles (for only a short time as the hypogeum was soon filled in with mechanisms to support the other activities), animal hunts, executions, re-enactments of famous battles, and dramas based on Classical mythology.

**Comment by andy5995** [comment]
>The only change that needs to be made is that when clicking the worker to build, the option to build a "forum" is there; that needs to be changed to "colosseum".

So in this case, after you make those changes,  you would commit, and then push. This PR will update automatically.

**Pull request closed without merging**
